---
label: default
hide_body: false
fields:
- type: include
  name: defaults
  label: defaults
  template: partial-default
- type: include
  name: image
  label: image
  template: partial-images-w-credit
- type: include
  name: weight
  label: weight
  template: partial-weight
- name: footer_copy
  type: text
  config:
    required: false
  label: Footer Copy
